if(NOT DEFINED SRC OR NOT DEFINED DST)
  return()
endif()
if(NOT EXISTS "${SRC}")
  return()
endif()
file(GLOB _dlls "${SRC}/*.dll")
foreach(_dll IN LISTS _dlls)
  execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${_dll}" "${DST}")
endforeach()
